sudo: required

language: go

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REPO_DOMAIN
  - docker build -t $DOCKER_REPO:$COMMIT .
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:latest
  - docker push $DOCKER_REPO
