sudo: required

language: go

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io
  - export REPO=quay.io/orfeasz/ecr-token-refresh
  - docker build -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker push $REPO
