apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spin-clouddriver-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: clouddriver
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: spin-clouddriver-v000
  template:
    metadata:
      labels:
        replication-controller: spin-clouddriver-v000
        load-balancer-spin-clouddriver: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/clouddriver:master
          imagePullPolicy: Always
          name: clouddriver
          ports:
            - containerPort: 7002
              name: clouddriver
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
            - mountPath: /root/.kube
              name: creds-config
            - mountPath: /opt/passwords
              name: password-volume
          readinessProbe:
            httpGet:
              path: /credentials
              port: 7002
            initialDelaySeconds: 20
            timeoutSeconds: 1
          - image: quay.io/skuid/ecr-token-refresh:latest
            imagePullPolicy: Always
            name: token-refresh
            volumeMounts:
              - mountPath: /opt/config/ecr-token-refresh
                name: refresh-config
              - mountPath: /opt/passwords
                name: password-volume
      volumes:
        - name: password-volume
          emptyDir: {}
        - name: refresh-config
          configMap:
            name: refresh.config
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
        - name: creds-config
          secret:
            secretName: creds-config